

spring:
  security:
    oauth2:
      client:
        #registration
        registration:
          naver:
            client-name: naver
            client-id: 4g1OL6yiojoAdETM9MKO
            client-secret: ${naver_client_secret}
            redirect-uri: http://loaclhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-name: google
            client-id: 565815610235-rj9vj5lmpsh0f5rh0pjaohrssgmkedpm.apps.googleusercontent.com
            client-secret: ${google_client_secret}
            redirect-uri: http://loaclhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

        #provider
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https:/openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OAuth2WithJWT?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: dydrkfl11!

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

